backend:
  name: git-gateway
  repo: kirsten/thejantar.com
  branch: master

publish_mode: editorial_workflow

media_folder: "assets/img"

collections:
  - name: "releases"
    label: "Releases"
    folder: "_releases"
    create: true
    fields:
      - { label: "Album Title", name: "title", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Record Label", name: "label", widget: "string", required: false }
      - { label: "Release Date", name: "date", widget: "datetime" }
      - { label: "Compilation?", name: "compilation", widget: "boolean", default: false }
      - { label: "Album Cover", name: "cover_image", widget: "image" }
      - label: "Tracks"
        name: "tracks"
        widget: "list"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Link", name: "link", widget: "string", required: false }
  - name: "data"
    label: "Data"
    editor:
      preview: false
    files:
      - label: "Shows"
        name: "shows"
        file: "_data/shows.yml"
        fields:
          - label: "Show List"
            name: "show_list"
            widget: "list"
            add_to_top: true
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Date, name: date, widget: datetime }
              - { label: Link, name: link, widget: string, required: false }
