backend:
  name: github
  repo: kirsten/thejantar.com
  branch: master
  publish_mode: editorial_workflow

media_folder: "assets/img"

collections:
  - name: "releases"
    label: "Releases"
    folder: "_releases"
    create: true
    fields:
      - { label: "Album Title", name: "title", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Record Label", name: "label", widget: "string" }
      - { label: "Release Date", name: "date", widget: "datetime" }
      - { label: "Compilation?", name: "compilation", widget: "boolean" }
      - { label: "Album Cover", name: "cover_image", widget: "image" }

